### ISSUE TITLE
Error on --help

### ISSUE THREAD

**Issue by VadVergasov** [Jylpah/blitz-tools#12]
Here is the log:

```
python .\analyze_wotb_replays.py --help
usage: analyze_wotb_replays.py [-h] [--output {json,plain,db}] [-id ACCOUNT_ID] [-a ACCOUNT] [-x] [-X [{tank_name,map_name,battle_i} [{tank_name,map_name,battle_i} ...]]] [--hist]
                               [--stat_func {tank_tier,player}] [-u] [--tankfile TANKFILE] [--mapfile MAPFILE] [-o OUTPUT] [--db] [--filters FILTERS] [-d] [-v] [-s]
                               FILE1 [FILE2 ...] [FILE1 [FILE2 ...] ...]

Analyze Blitz replay JSONs from WoTinspector.com

positional arguments:
  FILE1 [FILE2 ...]     Files/dirs to read. Use '-' for STDIN, "db:" for database

optional arguments:
  -h, --help            show this help message and exit
  --output {json,plain,db}
                        Select output mode: JSON, plain text or database
  -id ACCOUNT_ID        WG account_id to analyze
  -a ACCOUNT, --account ACCOUNT
                        WG account nameto analyze. Format: ACCOUNT_NAME@SERVER
  -x, --extended        Print Extended stats
  -X [{tank_name,map_name,battle_i} [{tank_name,map_name,battle_i} ...]], --extra_categories [{tank_name,map_name,battle_i} [{tank_name,map_name,battle_i} ...]]
                        Print Extended categories
  --hist                Print player histograms (WR/battles)
  --stat_func {tank_tier,player}
                        Select how to calculate for ally/enemy performance: tank-tier stats, global player stats
  -u, --url             Print replay URLs
  --tankfile TANKFILE   JSON file to read Tankopedia from. Default is "tanks.json"
  --mapfile MAPFILE     JSON file to read Blitz map names from. Default is "maps.json"
  -o OUTPUT, --outfile OUTPUT
                        File to write results. Default STDOUT
  --db                  Use DB - You are unlikely to have it
  --filters FILTERS     Filters for DB based analyses. MongoDB find() filter JSON format.
  -d, --debug           Debug mode
  -v, --verbose         Verbose mode
  -s, --silent          Silent mode
Cancelling an overlapped future failed
future: <_OverlappedFuture pending overlapped=<pending, 0x2c517fb8310> cb=[BaseProactorEventLoop._loop_self_reading()]>
Traceback (most recent call last):
  File "C:\Program Files\Python38\lib\asyncio\runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\Python38\lib\asyncio\base_events.py", line 603, in run_until_complete
    self.run_forever()
  File "C:\Program Files\Python38\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Program Files\Python38\lib\asyncio\base_events.py", line 570, in run_forever
    self._run_once()
  File "C:\Program Files\Python38\lib\asyncio\base_events.py", line 1859, in _run_once
    handle._run()
  File "C:\Program Files\Python38\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File ".\analyze_wotb_replays.py", line 668, in main
    args = parser.parse_args()
  File "C:\Program Files\Python38\lib\argparse.py", line 1768, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "C:\Program Files\Python38\lib\argparse.py", line 1800, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "C:\Program Files\Python38\lib\argparse.py", line 2006, in _parse_known_args
    start_index = consume_optional(start_index)
  File "C:\Program Files\Python38\lib\argparse.py", line 1946, in consume_optional
    take_action(action, args, option_string)
  File "C:\Program Files\Python38\lib\argparse.py", line 1874, in take_action
    action(self, namespace, argument_values, option_string)
  File "C:\Program Files\Python38\lib\argparse.py", line 1045, in __call__
    parser.exit()
  File "C:\Program Files\Python38\lib\argparse.py", line 2508, in exit
    _sys.exit(status)
SystemExit: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python38\lib\asyncio\windows_events.py", line 66, in _cancel_overlapped
    self._ov.cancel()
OSError: [WinError 6]
```

Windows 10 x64, Python 3.8

**Comment by VadVergasov** [comment]
No error on Ubuntu 18

**Comment by Jylpah** [comment]
Hello, just noticed this. This is weird. I run Ubuntu 20.04 on Win10 sub system for Linux and it's working fine. I checked on Windows side and I get the same issue. Let me check this.

**Comment by Jylpah** [comment]
This relates to Python 3.8 asyncio new behavior on Win platform. Same case here with workaround:
[https://github.com/iojw/socialscan/issues/13](https://github.com/iojw/socialscan/issues/13)

Fixed now. Thanks for reporting.
