### ISSUE TITLE
ERROR on analyze

### ISSUE THREAD

**Issue by VadVergasov** [Jylpah/blitz-tools#13]
Here is the log:

```
python .\analyze_wotb_replays.py -x -a VadVergasov_EU@EU .\tmp\
ERROR: get_tank_data(): Key not found : Exception: <class 'KeyError'> : '4993'
ERROR: read_replay_JSON():  : Exception: <class 'TypeError'> : '>' not supported between instances of 'NoneType' and 'int'
```

And after stats:

```
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000002CB9957F4C0>
Traceback (most recent call last):
  File "C:\Program Files\Python38\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Program Files\Python38\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Program Files\Python38\lib\asyncio\base_events.py", line 719, in call_soon
    self._check_closed()
  File "C:\Program Files\Python38\lib\asyncio\base_events.py", line 508, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
```

**Comment by VadVergasov** [comment]
On Ubuntu 18 all work well.

**Comment by Jylpah** [comment]
This relates to Python 3.8 asyncio new behavior on Win platform. Same case here with workaround:
[https://github.com/iojw/socialscan/issues/13](https://github.com/iojw/socialscan/issues/13)

Fixed now. Thanks for reporting.
