### ISSUE TITLE
No output file

### ISSUE THREAD

**Issue by VadVergasov** [Jylpah/blitz-tools#14]
No output file generated.
[replays.zip](https://github.com/Jylpah/blitz-tools/files/4841417/replays.zip) - Here is replays folder

```
python .\analyze_wotb_replays.py -a VadVergasov_EU@EU --output json -o output.json .\replays\
Fetching player stats |████████████████████████████▌   | 25/28 89% ETA 0 h 0 mins


TOTAL_______________   Battles      WR      DPB    Spot   Top tier   Player WR   Allies WR   Enemies WR   Allies Btls   Enemies Btls
               Total :    2     :   0.0% :  1780 :  2.5 :     100% :    72.06% :    50.17% :     52.63% :        2657 :         2614

Result______________   Battles      WR      DPB    Spot   Top tier   Player WR   Allies WR   Enemies WR   Allies Btls   Enemies Btls
                Loss :    2     :   0.0% :  1780 :  2.5 :     100% :    72.06% :    50.17% :     52.63% :        2657 :         2614

Battle Type_________   Battles      WR      DPB    Spot   Top tier   Player WR   Allies WR   Enemies WR   Allies Btls   Enemies Btls
           Encounter :    2     :   0.0% :  1780 :  2.5 :     100% :    72.06% :    50.17% :     52.63% :        2657 :         2614

Tank Tier___________   Battles      WR      DPB    Spot   Top tier   Player WR   Allies WR   Enemies WR   Allies Btls   Enemies Btls
                   8 :    2     :   0.0% :  1780 :  2.5 :     100% :    72.06% :    50.17% :     52.63% :        2657 :         2614

Tier________________   Battles      WR      DPB    Spot   Top tier   Player WR   Allies WR   Enemies WR   Allies Btls   Enemies Btls
            Top tier :    2     :   0.0% :  1780 :  2.5 :     100% :    72.06% :    50.17% :     52.63% :        2657 :         2614

Battle Medal________   Battles      WR      DPB    Spot   Top tier   Player WR   Allies WR   Enemies WR   Allies Btls   Enemies Btls
                   - :    2     :   0.0% :  1780 :  2.5 :     100% :    72.06% :    50.17% :     52.63% :        2657 :         2614
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000001D26764F4C0>
Traceback (most recent call last):
  File "C:\Program Files\Python38\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Program Files\Python38\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Program Files\Python38\lib\asyncio\base_events.py", line 719, in call_soon
    self._check_closed()
  File "C:\Program Files\Python38\lib\asyncio\base_events.py", line 508, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
```

**Comment by Jylpah** [comment]
This relates to Python 3.8 asyncio new behavior on Win platform. Same case here with workaround:
[https://github.com/iojw/socialscan/issues/13](https://github.com/iojw/socialscan/issues/13)

Fixed now. Thanks for reporting.

**Comment by Jylpah** [comment]
Oh, I was initially intending to write JSON output support, but never did so. I removed the option from --help printout. I do not thing implementing it would be a big issue, but I never had a need for it. 

The functionality should be added to: 
* process_battle_results()
* BattleRecordCategory.print_results()
* BattleRecord.print_results()

**Comment by Jylpah** [comment]
Oh, I was initially intending to write JSON output support, but never did so. I removed the option from --help printout. I do not thing implementing it would be a big issue, but I never had a need for it. 

The functionality should be added to: 
* process_battle_results()
* BattleRecordCategory.print_results()
* BattleRecord.print_results()
